# Generated by Django 6.0.3 on 2026-04-07 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_type',
            field=models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiple'), ('rating', 'Échelle 1 à 5'), ('text', 'Texte libre')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='vote',
            name='answer_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.choice'),
        ),
    ]
